_wandb:
    value:
        cli_version: 0.21.0
        e:
            zbh2zr2jq8ye80wui1x5jrw4mk24wexb:
                codePath: mcp_version/client.py
                codePathLocal: client.py
                cpu_count: 56
                cpu_count_logical: 112
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "2005769203712"
                        used: "1783198822400"
                email: wguo6358@gmail.com
                executable: /home/wg25r/miniconda/envs/neg/bin/python3
                git:
                    commit: f2246a6373e68c67cb363038d4915837a372fa1b
                    remote: https://github.com/weathon/AAv2.git
                gpu: NVIDIA RTX A6000
                gpu_count: 3
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-058c2ff8-0e0d-ba79-96b8-99c5bdc85e8e
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-292c05d7-cef3-261e-b438-24530c206940
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-223f1d69-b595-dd22-d112-fae575ae6ef4
                host: shandu.ws.ok.ubc.ca
                memory:
                    total: "810125438976"
                os: Linux-6.8.0-94-generic-x86_64-with-glibc2.35
                program: /home/wg25r/aas2/AAv2/mcp_version/client.py
                python: CPython 3.10.17
                root: /home/wg25r/aas2/AAv2/mcp_version
                startedAt: "2026-02-16T09:43:58.332395Z"
                writerId: zbh2zr2jq8ye80wui1x5jrw4mk24wexb
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 15
                - 95
                - 105
            "2":
                - 15
                - 95
                - 105
            "3":
                - 13
            "4": 3.10.17
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
